### ISSUE TITLE
Failure occurred while calculating the fact. System.InvalidOperationException

### ISSUE THREAD

**Issue by Itua-Juele** [GetcuReone/FactFactory#265]
2021-03-09 15:24:06.9554 | ERROR | System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   в GetcuReone.FactFactory.FactFactoryHelper.GetFact[TFact](IEnumerable`1 facts)
   в GetcuReone.FactFactory.BaseEntities.FactRuleCollectionBase`1.<>c__DisplayClass21_0`3.<Add>b__0(IEnumerable`1 facts)
   в GetcuReone.FactFactory.BaseEntities.FactRuleBase.Calculate(IEnumerable`1 requireFacts)
   в GetcuReone.FactFactory.Facades.SingleEntityOperations.SingleEntityOperationsFacade.<>c__DisplayClass10_0`3.<CalculateFact>b__0(IEnumerable`1 facts)
   в GetcuReone.ComboPatterns.Factory.FactoryBase.CreateObject[TParameter,TObj](Func`2 factoryFunc, TParameter parameter)
   в GetcuReone.FactFactory.Facades.SingleEntityOperations.SingleEntityOperationsFacade.CalculateFact[TFactRule,TWantAction,TFactContainer](NodeByFactRule`1 node, IWantActionContext`2 context)
   в GetcuReone.FactFactory.Priority.Facades.SingleEntityOperations.PrioritySingleEntityOperationsFacade.CalculateFact[TFactRule,TWantAction,TFactContainer](NodeByFactRule`1 node, IWantActionContext`2 context)
   в GetcuReone.FactFactory.Versioned.Facades.SingleEntityOperations.VersionedSingleEntityOperationsFacade.CalculateFact[TFactRule,TWantAction,TFactContainer](NodeByFactRule`1 node, IWantActionContext`2 context)
   в GetcuReone.Cdi.FactFactory.GrSingleEntityOperationsFacade.CalculateFact[TFactRule,TWantAction,TFactContainer](NodeByFactRule`1 node, IWantActionContext`2 context)
   в GetcuReone.FactFactory.Facades.TreeBuildingOperations.TreeBuildingOperationsFacade.<>c__DisplayClass10_0`3.<CalculateTreeAndDeriveWantFactsAsync>b__0(NodeByFactRule`1 node)
   в System.Collections.Generic.List`1.ForEach(Action`1 action)
   в GetcuReone.FactFactory.Facades.TreeBuildingOperations.TreeBuildingOperationsFacade.<CalculateTreeAndDeriveWantFactsAsync>d__10`3.MoveNext()

**Comment by GetcuReone** [comment]
Try to download the latest version of the package. There should be more details about the error. If the problem is still not resolved, then reopen the issue
